### PR TITLE
Clustering docs

### PR DESCRIPTION
**Pull request by sez11a**
Clustering Documentation for your review.

### CODE REVIEW

**Comment by sez11a** [comment]
The only file you need to worry about is the one in develop/tutorials/articles-dxp/02-configuring-liferay/03-liferay-clustering.markdown. The doc repo ones are from another branch that got split off from this one.

**Comment by tinatian** [comment]
OK. Thanks @sez11a ! Will try to finish it up soon.

**Comment by tinatian** [comment]
@sez11a 
I read through the doc you mentioned, and there are something I found:
1) Cache replication, sorry I did not say it clearly in the doc, I modified the doc and please check my changes.
2) Bind address setting, my bad too, I did not say it clearly, I made some changes, please check the doc again
3) Since CE does not support cluster, all the cluster related features needs extra bundles to enabled. To enable cluster, you need "portal-cluster-multiple" ; To enable cache replication, you need "portal-cache-multiple"; To enable scheduler work correctly across cluster, you need "portal-scheduler-multiple" . So it means "Enabling Cluster Link automatically WILL NOT activate distributed caching" unless you have the required bundles.
4) For different protocols used by jGroups like TCP, JDBCPing and so on, it is not provided by our EE code, all of them are provided by jGroups.
5) For big-memory usage, I think I sent you a doc about that earlier, please let me know if you can not find.

Any question, please feel free to let me know.


Tina.

**Comment by sez11a** [comment]
@tinatian For #5, I can't find this document; can you resend it? 

For #1, I'm not sure we need to state this anymore like we did for 6.2. In 6.2, because we supported clustering on both CE and EE, we needed to mention the deployable cache replication algorithm. Since we now no longer support clustering on CE and we don't make the module available to CE users, I planned to say only that we have an optimized cache replication algorithm. This also covers #3: these bundles will not be available to CE users, so there's no need to talk about them. Is that okay? 

I will clarify #4. 

Thanks!

**Comment by tinatian** [comment]
Yes, just shared it with you, please see https://docs.google.com/document/d/1Bcuw0pb4av_mar4h4eMk7sauEeob8xkH7EBwLGAfV-w/edit#

For #1 #3, you can say what you want, I just want you to know what is the truth. I am OK with whatever you are going to say in the doc as long as they are right.

Tina.

**Pull request closed without merging**
